작성한 프로그램을 Test하기 위한 용도로 활용하는 python의 `pytest`모듈에 대해 알아보겠습니다.  
아래의 글은 [이곳](https://www.tutorialspoint.com/pytest/pytest_fixtures.htm)을 바탕으로 작성되었습니다.


먼저, `pytest`모듈은 아래와 같이 pip를 활용하여 설치할 수 있습니다.  
특정 버전을 설치하고 싶으면, pytest==2.9.1과 같이 버전을 명시하면 됩니다. 

```python
pip install pytest
```

pytest는 다른 설정이 없으면 디폴트로 `test_*.py` 혹은 `*_test.py` 형태의 파일을 테스트합니다.  
파일 내에서는 `test*`형태의 함수를 실행하게 됩니다.  

아래와 같이 예제 파일을 만들어봅니다.
```python
#test_square.py
import math

def test_sqrt():
   num = 25
   assert math.sqrt(num) == 5

def testsquare():
   num = 7
   assert 7*7 == 40

def tesequality():
   assert 10 == 11
```

커맨드라인에 `pytest`를 실행해보면, 아래와 같은 결과가 나옵니다. 

```text
test_square.py .F
============================================== FAILURES 
==============================================
______________________________________________ testsquare 
_____________________________________________
   def testsquare():
   num=7
>  assert 7*7 == 40
E  assert (7 * 7) == 40
test_square.py:9: AssertionError
================================= 1 failed, 1 passed in 0.06 seconds 
=================================
```
2개의 테스트 작업(함수)이 detect되었고, 1개는 실패, 1개는 성공하였음을 나타내고 있습니다.  
아래와 같이 py 파일을 하나 더 생성해봅니다. 
```python
# test_compare.py
def test_greater():
   num = 100
   assert num > 100

def test_greater_equal():
   num = 100
   assert num >= 100

def test_less():
   num = 100
   assert num < 200
```
`pytest -v`커맨드로 실행을 시켜보면, 아래와 같은 결과가 나옵니다. pytest는 현재 디렉토리와 모든 하위 디렉토리에서 test 작업을 확인해 모두 실행하고 결과를 반환합니다. 

```text
test_compare.py::test_greater FAILED
test_compare.py::test_greater_equal PASSED
test_compare.py::test_less PASSED
test_square.py::test_sqrt PASSED
test_square.py::testsquare FAILED
================================================ FAILURES 
================================================
______________________________________________ test_greater 
______________________________________________
   def test_greater():
   num = 100
>  assert num > 100
E  assert 100 > 100

test_compare.py:3: AssertionError
_______________________________________________ testsquare 
_______________________________________________
   def testsquare():
   num = 7
>  assert 7*7 == 40
E  assert (7 * 7) == 40

test_square.py:9: AssertionError
=================================== 2 failed, 3 passed in 0.07 seconds 
===================================
```

특정 파일만을 실행시키고 싶으시면, 아래와 같이 파일명을 명시해주시면 됩니다. 
```text
pytest test_compare.py -v
```
실제 다수의 테스트 파일이 있고, 한 파일에 많은 테스트 케이스들이 존재하는 경우가 많을 것입니다. 이때 테스트 케이스의 부분집합에 대해서만 실행하고 싶은 경우에 대해 알아보겠습니다.  

pytest는 아래의 두 가지 방법을 지원합니다. 
* test 이름의 substring으로 특정 그룹을 지칭하여 실행
* marker를 활용해 해당 marker에 해당하는 테스트들만 실행

substring을 포함한 테스트케이스만 실행하는 것은 아래의 커맨드를 이용하면 됩니다. 
```
pytest -k <substring> -v
```
만약 great가 포함된 테스트 케이스만 실행하고 싶다면 다음과 같은 명령어로 실행시키면 됩니다. 
```
pytest -k great -v
```

실행 결과는 아래와 같습니다. 
```
test_compare.py::test_greater FAILED
test_compare.py::test_greater_equal PASSED
============================================== FAILURES 
==============================================
____________________________________________ test_greater 
____________________________________________
def test_greater():
num = 100
>  assert num > 100
E  assert 100 > 100
test_compare.py:3: AssertionError
========================== 1 failed, 1 passed, 3 deselected in 0.07 seconds 
==========================
```

marker를 활용하는 경우 py 파일 내에서, 각각의 test 함수에 아래와 같이 표시를 해두어야 합니다. 
```python
@pytest.mark.<markername>
```
즉, 기존에 작성된 파일을 아래와 같이 바꾸어주면 됩니다. 이때 pytest 모듈을 import 해주어야 합니다. 
```python
# test_compare.py 수정
@pytest.mark.great
def test_greater():
   num = 100
   assert num > 100

@pytest.mark.great
def test_greater_equal():
   num = 100
   assert num >= 100

@pytest.mark.others
def test_less():
   num = 100
   assert num < 200

```
마찬가지로, `test_square.py`도 수정해주었다고 칩시다.  
아래의 명령어를 실행하게 되면, `others` 마커가 붙은 함수만 실행이 됩니다. 
```
pytest -m others -v
```
```
test_compare.py::test_less PASSED
test_square.py::test_equality FAILED
============================================== FAILURES
==============================================
___________________________________________ test_equality
____________________________________________
   @pytest.mark.others
   def test_equality():
>  assert 10 == 11
E  assert 10 == 11
test_square.py:16: AssertionError
========================== 1 failed, 1 passed, 4 deselected in 0.08 seconds
==========================
```



